### ISSUE TITLE
The cuddling animation no longer works in my game :c

### ISSUE THREAD

**Issue by ODF4** [enjarai/blahaj-of-undying#10]
I just noticed that with the new 1.7.0 update, holding a plushie doesn't show the hugging animation anymore...

My Minecraft version is 1.21.1, with Fabric API 0.103.0.

This seems to be a conflict with the `continuity-3.0.0-beta.5+1.21` mod, but I know that they weren't conflicting in version 1.6.0.
I tried to run the game with only Fabric API and Blåhaj of Undying installed and that seems to fix the issue, although even in this case there seems to no longer be a smooth animation of the arms when going from holding a regular item (or nothing) to holding a plushie, and vice versa.
I also tried updating Fabric API to 0.104.0, but nothing changed.
Also, this issue seems to happen regardless of whether the three built-in resource packs from the two mods (Default to Totem, Default Connected Textures, and Glass Pane Culling Fix) are enabled or not.

Steps to reproduce the issue:
- Install Fabric API, Blåhaj of Undying 1.7.0, and [continuity-3.0.0-beta.5+1.21](https://modrinth.com/mod/continuity/version/3.0.0-beta.5+1.21)
- Run Minecraft 1.21.1 and enter any world
- press F5 twice and hold a plushie

I will gladly provide additional information if needed. Thank you so much for your support!

**Comment by enjarai** [comment]
I'm not able to recreate this issue using the steps you give, but I've looked into Continuity's code, and I see something that *could* be the issue... Mind if I get back to you with a mod jar you can try to see if that fixes it?

**Comment by ODF4** [comment]
> I'm not able to recreate this issue using the steps you give, but I've looked into Continuity's code, and I see something that _could_ be the issue...

The only other thing that comes to my mind at the moment is that I haven't tried removing my other resource packs (Vanilla Tweaks + a few CIT packs), so maybe it's one of those that "activates" the conflict? I'll test this later today and let you know if that changes anything, but as I said before, using only these three mods (Fabric API included) is enough for me to experience the issue 

> Mind if I get back to you with a mod jar you can try to see if that fixes it? If I can't recreate it, I can't really test it myself...

Sure thing! And actually thank you so much for still trying to help me without being able to replicate the issue, I'm so sorry to bother you with this

**Comment by ODF4** [comment]
I finally found what causes it! Other than the steps I previously mentioned, you also need to use the Vanilla Tweaks resource pack, and you specifically need to enable one or both of the two "Fully Aged X Marker" options in the Utility section.

![immagine](https://github.com/user-attachments/assets/7274511f-23a2-4dcf-97ba-dbc18eb88834)

So the updated steps to reproduce the issue are:

- install Fabric API, Blåhaj of Undying 1.7.0, and [continuity-3.0.0-beta.5+1.21](https://modrinth.com/mod/continuity/version/3.0.0-beta.5+1.21)
- run Minecraft 1.21.1 and enter any world
- create a [Vanilla Tweaks resource pack](https://vanillatweaks.net/picker/resource-packs/) that includes either "Fully Aged Crop Marker" or "Fully Aged Amethyst Cluster Marker", and enable the resource pack in the game
- press F5 twice and hold a plushie

That's such a weird string of coincidences that causes this issue! But as I said before, not only did I not experience this with version 1.6.0 of the Blåhaj of Undying mod, but it seems like there is no longer a smooth arms animation when holding plushies now, so you immediately jump from low arms to hugging animation with no in-between frames.

**Comment by enjarai** [comment]
This mod by itself does not add any animation to the arms, it has always instantly snapped to the custom pose. I'm assuming another mod is implementing that, probably Not Enough Animations. Do correct me if I'm wrong tho.

I have an idea whats causing this. Continuity wraps certain models with its own implementation when resource packs require it to, which blahaj does not account for with the custom model property I added in the update. I'll test a fix and release it if it works.

**Comment by enjarai** [comment]
Fixed in 1.7.1.

**Comment by ODF4** [comment]
> This mod by itself does not add any animation to the arms, it has always instantly snapped to the custom pose. I'm assuming another mod is implementing that, probably Not Enough Animations. Do correct me if I'm wrong tho.

That's correct, it was Not Enough Animations doing that!

> Fixed in 1.7.1.

And I can confirm that the bug was fixed in the new version, thank you so much for fixing it so quickly!
