### ISSUE TITLE
[ENHANCEMENT] Match Totem Particle Theme with Blahaj's Colors

### ISSUE THREAD

**Issue by leeineian** [enjarai/blahaj-of-undying#3]
(blue and white particles around the player when the totem is used)

**Comment by enjarai** [comment]
Thats a good idea! I'll have to see how feasible it is to implement, but I definitely like it.

**Comment by enjarai** [comment]
This is now added as of 1.3.0! Any of the 33 custom blahaj skins will have matching totem particles when popped. The default skin still has vanilla particles though.
