### ISSUE TITLE
Doesnt change the model :(

### ISSUE THREAD

**Issue by Gimgajim** [enjarai/blahaj-of-undying#5]
The mod doesnt change the texture into the model :(
![image](https://github.com/enjarai/blahaj-of-undying/assets/91958828/dbc74f12-76f5-4999-8768-351fcef0ea05)

**Comment by enjarai** [comment]
You might be using a texture pack that overrides the totem model, try making sure the "Fabric Mods" resource pack is at the top of your active packs list.

**Comment by Gimgajim** [comment]
> You might be using a texture pack that overrides the totem model, try making sure the "Fabric Mods" resource pack is at the top of your active packs list.

works now, ty :D
