### ISSUE TITLE
No bread pillow? :c

### ISSUE THREAD

**Issue by ODF4** [enjarai/blahaj-of-undying#7]
This mod is amazing, and it's even better now that I discovered that it also includes Blåvingad and the other plushies, but why was the bread pillow from hibi's mod left out? :c

![preview_bread](https://github.com/user-attachments/assets/1f221a5c-b5b2-44c5-8b4a-29c390ec5247)

Any plans to include it in a future update (and assign the "baguette" keyword to it)? Regardless, thank you so much for developing such a cute client-side mod!

**Comment by enjarai** [comment]
Ah, right. I actually forgot about that one. I'll put it on my todo list. :3

**Comment by Crephan** [comment]
> It might be cool to implement even more plushies eventually
I make the additional plushies for the mod. Already got more anime character based plushies planned, but if you got any non-human type plushies to recommend, then please feel absolutely free to share your suggestions. :3

**Comment by enjarai** [comment]
> a config filter with wildcards (maybe with regular expressions?) to assign the cuddling animation to any item we want (which I think would work great with some resource packs + CIT Resewn/Optifine)

Great idea! I've just implemented this:

![](https://i.enjarai.dev/u/24YT6z.png)

Any thoughts?

**Comment by ODF4** [comment]
> Any thoughts?

This seems like a much better way of implementing my idea!

However I do feel like including an additional pattern matching config that users can modify themselves might allow for more flexibility, since existing resource packs might not support this new property for a while.

My idea was to store a string such as `matching=bread/* pillow/*baguette*` in the mod's config file, which would apply the hugging animation to any item that has those words in its name (in this example, the default Minecraft bread would become huggable, as well as any other item renamed "bread", any renamed item that ends in " pillow", and any renamed item that contains the word "baguette" anywhere in its name).

I took inspiration for the pattern matching that uses "/" as "or" from the [Tasker for Android implementation documented here](https://tasker.joaoapps.com/userguide/en/matching.html), but I'm fairly sure that using only slashes and asterisks (+ a way to escape these characters?) in the mod would suffice.

**Comment by ODF4** [comment]
> I can look into that, but I'm trying to avoid having a config file honestly. I'd prefer to define everything via resource packs, so that two players that have the same packs are guaranteed to have the same working plushies.

That's a great point which I really hadn't considered!
If you do decide to implement a config file at some point, maybe you could nudge users into avoiding custom configs with an in-game warning that pops up whenever users are about to edit the config file? I think that could make users aware that editing the config is only a client-side change and they'd need to share the same string with other players if they want to make sure to sync their animations.
If players could simply share their string as a clickable command in chat (something like `Click here to copy your friend's pattern matching!` and when you click it, it would send a command like `/blahaj match "bread/* pillow/*baguette*"` automatically) that would be seriously amazing, but at the same time it would definitely make the mod much more complex.
Also, if you're going to implement the warning pop-up, I think you should also include a "Don't show this message again" checkbox, maybe with a boolean in the config file?
But yeah, I completely understand if you'd rather not implement this at all, no worries!

> We're primarily adding IKEA and queer character plushies, as this is definitely a pride focused mod. Since I'm transfem myself, we're currently mostly focusing on femboys and transfem characters, but more representation is definitely on the table. Let me know if you have any ideas in that area!

That makes a lot of sense! In this case I'm not really sure of any characters that might fit the theme, but if I can think of any I'm definitely gonna let you know! And on the same topic, I don't know if you'd rather not include the bread pillow for this same reason, but if you will I'd really appreciate it! I could even try to make some pride textures for multiple bread pillows if you'd like :3

> Love to hear that!! ❤️ We're currently the only ones working on the mod. I do the code, while Crephan has been making assets and models recently.

That's genuinely impressive! And once again I'm really looking forward to seeing how this mod expands over time, so I wish you two the best of luck with its development! Thank you so much again for all your work! <3

**Comment by Crephan** [comment]
> I don't know if you'd rather not include the bread pillow for this same reason, but if you will I'd really appreciate it!

Don't worry, before you even wrote this comment I already made a new remastered version of the bread plush with a new texture. You can expect it in probably the next update.

> I could even try to make some pride textures for multiple bread pillows if you'd like :3

As for this, we don't hate the idea or anything, but again this mod is designed to keep the blahaj as it's mascot and so features like pride textures aren't planned to be brought to other plushies. The rough idea is to make at least half of the mod consist of pure blahaj content.

**Comment by ODF4** [comment]
> Don't worry, before you even wrote this comment I already made a new remastered version of the bread plush with a new texture.

That's awesome, thank you so much for that, I really can't wait to see it! :D

Should I close this issue? Feel free to do so if you wish!

> As for this, we don't hate the idea or anything, but again this mod is designed to keep the blahaj as it's mascot and so features like pride textures aren't planned to be brought to other plushies. The rough idea is to make at least half of the mod consist of pure blahaj content.

And don't worry about it at all, I completely understand! It makes perfect sense for the mod's content to be mainly centered around Blåhaj, considering that's in the title itself!

**Comment by enjarai** [comment]
Just published 1.7.0 with the features we've discussed here! Note that we couldnt assign the `baguette` keyword to the bread, since thats already used by Bridget (my beloved)

**Comment by Crephan** [comment]
I would assume that is a problem caused by incompatibility with another mod, as both Rai and I don't encounter this issue at all. Do you happen to have any player animation mods installed?

**Comment by ODF4** [comment]
> I would assume that is a problem caused by incompatibility with another mod, as both Rai and I don't encounter this issue at all. Do you happen to have any player animation mods installed?

I also thought that it might be that mod but somehow it's the Continuity mod that causes it. I opened a new issue with more info but yeah that's pretty odd in my opinion
