### ISSUE TITLE
Change the orientation and scale of the plushies when placed in item frames

### ISSUE THREAD

**Issue by ODF4** [enjarai/blahaj-of-undying#9]
I just thought of this idea for the mod, but I want to preface this by saying that I'm not sure if this can be implemented without affecting the orientation of the models when held by the player.

I think it could be really cool if you could put plushies inside item frames placed on top of blocks to use them as decoration. This would be similar to how some custom item texture resource packs work, such as Mizuno's 16 Craft CIT PACK or ItemBound: Rebound.
I also think that the plushies placed in item frames should be bigger than they currently are, so that they are the same size as when held by the player.

![item frames](https://github.com/user-attachments/assets/61bd28d1-7d70-4493-9141-5353225ea6ad)

**Comment by Crephan** [comment]
So the reason they currently look like this in item frames is due to the fact the majority of players hang item frames on walls. In vanilla Minecraft custom models only support a single local orientation for item frames. Rai said she _could possibly_ implement your suggestion for plushies added by the mod itself, but that it would be hard.

Also, the reason plushies aren't that big in item frames is because if they were huge, they would start clipping into other blocks. If you want your blahaj to be larger inside an item frame, then just use the large variant of the plush.

**Comment by ODF4** [comment]
> So the reason they currently look like this in item frames is due to the fact the majority of players hang item frames on walls. In vanilla Minecraft custom models only support a single local orientation for item frames. Rai said she _could possibly_ implement your suggestion for plushies added by the mod itself, but that it would be hard.

It would makes sense to keep things the way they are now, especially if other people already put the plushies in item frames as you described. And yeah I thought this might be complex to implement so don't worry about it at all!

> Also, the reason plushies aren't that big in item frames is because if they were huge, they would start clipping into other blocks. If you want your blahaj to be larger inside an item frame, then just use the large variant of the plush.

And I completely forgot about the "large" variants, so thank you for reminding me!

I guess we can close the issue then? Feel free to do so!

**Comment by Crephan** [comment]
Maybe. It depends on if @enjarai still wants to go out of her way to do something about it or not. :)

**Comment by enjarai** [comment]
I think this is out of scope for now, so I'll close this issue. I may look into it in the future if I find the time...

**Comment by ODF4** [comment]
> I think this is out of scope for now, so I'll close this issue. I may look into it in the future if I find the time...

Not a problem at all, don't worry about it!
